### ISSUE TITLE
Cookie Bar with Custom View not appearing from the bottom 

### ISSUE THREAD

**Issue by jobernas** [AviranAbady/CookieBar2#10]
When I set the Cookie Position to Bottom with a Custom View, the animation comes from the bottom but it only stops at the top. It does not stop to the bottom of the window.

**Comment by jobernas** [comment]
I compared the layout of my custom view it the default from the library and the main diference was the property     android:layout_gravity="bottom" on the  android:id="@+id/cookie" container.
I added this to my Custom layout and it worked. Now it sticks at the bottom. 

I don't know if you wanna leave this information for other developers that have this issue. Would be cool if the lib add this property by us if the position is Bottom.

By the way, thanks for this cool lib.

**Comment by AviranAbady** [comment]
Thanks @jobernas, will be fixed in the next version.

**Comment by AviranAbady** [comment]
Closing issue, fix included in release 1.1.2
