### ISSUE TITLE
Default padding 

### ISSUE THREAD

**Issue by MinaWadee** [AviranAbady/CookieBar2#12]
please i want to remove the default padding in custom design

**Comment by AviranAbady** [comment]
Hey @MinaWadee.
What default padding? When you use a custom layout, you control the entire view, including the padding.

**Comment by MinaWadee** [comment]
hey @AviranAbady 
in your code you add a default padding  
 int padding = getContext().getResources().getDimensionPixelSize(R.dimen.default_padding);
        if (layoutGravity == Gravity.BOTTOM) {
            layoutCookie.setPadding(padding, padding, padding, padding);
        }
(dimen.default_padding) i want to set  my custom padding which is "0dp"

**Comment by AviranAbady** [comment]
@MinaWadee, You are correct, thanks for the input.

In the next version I will add a way to set globaly the padding value.

For now, you can easily workaround the issue using by setting a dimen value with the same name in your project (app module), it will override the value set by cookiebar2.

**Comment by MinaWadee** [comment]
@AviranAbady thank you for your support

**Comment by AviranAbady** [comment]
@MinaWadee feature has been added, cookie padding can be set globally using the `cookiePadding` attribute.

`<item name="cookiePadding">50dp</item>`

Released in version 1.1.2
