### ISSUE TITLE
Swipe Listener

### ISSUE THREAD

**Issue by AhmedDroid** [AviranAbady/CookieBar2#14]
Hello,

Is there a way so that I can attach a listener on the swipe action from the user?

**Comment by AviranAbady** [comment]
Hey @AhmedDroid, not at the moment.
I will add the ability in the next release.

**Comment by AhmedDroid** [comment]
I can add it if you like, any help is appreciated.

**Comment by AviranAbady** [comment]
@AhmedDroid 
sure, pull requrests are always welcome

**Comment by AviranAbady** [comment]
fixed in the following [commit](https://github.com/AviranAbady/CookieBar2/commit/18b54d3b5a50b98e03364be6e59162d050751bba), will be released in v1.1.3
