### ISSUE TITLE
setTextAlignment(View.TEXT_ALIGNMENT_CENTER);

### ISSUE THREAD

**Issue by TheCroid** [AviranAbady/CookieBar2#21]
Please Aviran
Would you be able to add text alignment in this great library ?
Thanks

**Comment by AviranAbady** [comment]
Hey @TheCroid, do you mean for setting the alignment of the message text?
As an interim solution you can fully customize the look of the `Cookie` using `setCustomView(R.layout.custom_cookie)`

**Comment by TheCroid** [comment]
Yes @AviranAbady for messsage text 
:-) thank you very much
