### ISSUE TITLE
chekc error below i am getting when tab changing the cookie dialog reclose when again click on tab why

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [AviranAbady/CookieBar2#24]
![5f056e2112bf1918493242](https://user-images.githubusercontent.com/10194731/86888009-20fbc180-c117-11ea-9ec9-99595084f0f9.gif)

**Comment by AviranAbady** [comment]
@sunil-singh-chaudhary  please provide a sample project so I could examine the issue.

**Comment by AviranAbady** [comment]
@sunil-singh-chaudhary again, please provide an example project (upload to github) showcasing issue you are reporting or I will have to close the issue.

Thanks.

**Comment by AviranAbady** [comment]
Looking at the image in your issue, it's clear that you are not using an actual transparent image. The image has a checkered background mimicking the usual transparent visualization. 

Closing the issue.
