### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by headsvk** [AviranAbady/CookieBar2#30]
Hello, is this project still maintained?
Can you publish it to MavenCentral since JCenter is approaching end of life?
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by AviranAbady** [comment]
Hey @headsvk , yes Cookiebar2 is still very much maintained :) it will be migrated from jcenter soon.

**Comment by headsvk** [comment]
Awesome!
