### ISSUE TITLE
Add enable/disable auto dismiss for cookies.

### ISSUE THREAD

**Issue by zCode93** [AviranAbady/CookieBar2#6]
Add the ability to enable/disable auto dismiss

**Comment by AviranAbady** [comment]
Hey @zCode93, thanks for the input. I'll add a non-dismiss option in the next version.

**Comment by AviranAbady** [comment]
@zCode93 Version 1.1.0 has been released.
Two new functions have been added
setEnableAutoDismiss(boolean) - When set to false, auto dismiss is disabled
setSwipeToDismiss(boolean) -  Wen set to false, swiping off the view is disabled

Let me know if you need further assistance.
