### ISSUE TITLE
Default Bar Layout Issue

### ISSUE THREAD

**Issue by zCode93** [AviranAbady/CookieBar2#9]
Using the default cookie bar layout, there's margins issues. Specially between the image and text (including Title and Message). And if you want to show the the bar without a title, just having an icon and a message, overlap will be noticed.
I was using **v1.0.9** and it was working fine.

Following are the code, removed original text for this issue:

`CookieBar.build(activity)
                .setMessage("Test")
                .setBackgroundColor(R.color.winfooz_color_accent)
                .setIcon(R.drawable.ic_lock_unlocked_24dp)
                .setEnableAutoDismiss(false)
                .setSwipeToDismiss(true)
                .setAction("Action") {
                   // Handle action
                }
                .show()`

![screenshot from 2019-01-28 10-14-20](https://user-images.githubusercontent.com/13524763/51822627-9558f100-22e5-11e9-9b9e-fee4710e8e07.png)

**Comment by AviranAbady** [comment]
@zCode93 please provide a github sample project demonstrating the issue.

**Comment by AviranAbady** [comment]
@zCode93 I cant recreate the issue on my end, please provide a sample project, or I will have to close the issue.

Thanks.

**Comment by zCode93** [comment]
@AviranAbady I've added a comment where the icon margin has been removed from code

**Comment by AviranAbady** [comment]
Thanks @zCode93, looking into it.

**Comment by AviranAbady** [comment]
@zCode93 version 1.1.1 has been released, please let me know if the issue has been resolved.

**Comment by zCode93** [comment]
Yes it has been resolved. Thank you @AviranAbady
